arch: arm64
os: linux
dist: focal
language: rust
install:
  - cargo build --release
addons:
  ssh_known_hosts: github.com
script:
  - mkdir -p ~/.ssh
  - mv ./id_rsa.pub ~/.ssh/id_rsa.pub
  - openssl aes-256-cbc -d -a -in id_rsa.enc -out id_rsa -pass pass:${PASSPHRASE}
  - mv id_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
    #- ssh-keyscan -t rsa github.com 2>&1 >> ~/.ssh/known_hosts
  - git clone git@github.com:meltdownnn/bishojo-db.git
  - cat bishojo-db/x* > bishojo-db/database.bin && rm -f bishojo-db/x*
  - mv bishojo-db/database.bin database.bin; mv bishojo-db/database.json database.json
  - cargo run --release -- -r 20 -t 2 --timeout 60 fetch-metadata --end-page 200 --site kkgal --start-page 1
  - cargo run --release -- -r 20 -t 2 --timeout 60 download-images
  - cargo run --release -- -r 20 -t 2 --timeout 60 download-user-avatars --site kkgal
  - mv database.bin bishojo-db/database.bin
  - mv database.json bishojo-db/
  - git config --global user.name "meltdownnn"
  - git config --global user.email "75382863+meltdownnn@users.noreply.github.com"
  - bash -c "cd bishojo-db; split -b 90m database.bin; rm database.bin; git add *; git commit -m \"Automatic build\"; git gc --aggressive --prune; git push"
  - rm ssh_key
cache:
  cargo: true
