language: rust
env:
  global:
    - GIT_SSH_COMMAND: "ssh -i ssh_key -o IdentitiesOnly=yes"
install:
  - cargo build --release
script:
  - echo "${BISHOJO_PRIVATE_KEY}" > ssh_key
  - sh -c "${GIT_SSH_COMMAND} git clone https://github.com/meltdownnn/bishojo-db.git"
  - sh -c "[[ -f bishojo-db/database.bin ]] && (echo \"Using existing database from git\"; cp bishojo-db/database.bin database.bin; cp bishojo-db/database.json database.json) || true"
  - cargo run --release -- -r 20 -t 2 --timeout 60 fetch-metadata --end-page 200 --site kkgal --start-page 1
  - cargo run --release -- -r 20 -t 2 download-images
  - cargo run --release -- -r 20 -t 2 download-user-avatars --site kkgal
  - cp database.bin bishojo-db/
  - cp database.json bishojo-db/
  - git config --global user.name "meltdownnn"
  - git config --global user.email "75382863+meltdownnn@users.noreply.github.com"
  - sh -c "cd bishojo-db; git add *; git commit -m \"Automatic build\";${GIT_SSH_COMMAND} git push"
  - rm ssh_key
cache:
  cargo: true
